### ISSUE TITLE
Lower the precision for blind position

### ISSUE THREAD

**Issue by timdonovanuk** [pink88/Tuiss2HA#45]
Hi,

Thank you for your work on this, it works great for me!

Is there a way to lower the prevision for the blind position? While the blind is moving, my dashboard shows an insane number of decimal places:

![Image](https://github.com/user-attachments/assets/ceea2e68-2050-4c13-9f7d-933e7c018e1f)

It's fine when it's stopped (i.e. it'll settle on 50% or 100%). As the position is an attribute and not a sensor, I cannot find a way to set this easily in HA.

Thanks!

**Comment by pink88** [comment]
Interesting, Could you let me know what card you are using in that
screenshot, so I can replicate it?

Thanks

**Comment by timdonovanuk** [comment]
The bottom one is just the normal HA entities one, and the top one is from https://github.com/tungmeister/hass-blind-card. 

```
type: grid
cards:
  - type: heading
    heading: New section
  - type: custom:compact-cover-control-card
    rooms:
      - name: Study
        covers:
          - name: Window
            entity: cover.study_blind
  - type: entities
    entities:
      - entity: cover.study_blind
        secondary_info: position
    state_color: true
```

There is also an issue where sometimes if you use the controls on the card, Tuiss2HA doesn't seem to update the blinds position in HA. It's only sometimes, I need to play around with what triggers the position to be updated and what doesn't.

Thanks for taking a look so quickly! Cheers.
